/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3ac36688-8de7-4b79-9c1a-4e54605fa17d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7KmZwV2qm",
    "aws_user_pools_web_client_id": "4dghft82rirko70rqe65ejg9eq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bdkqgsrddrhtfp3kqbdqzfougm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
